name: CraftlandiaRails
author: catageek, sync667
description: An automatic transit system
main: com.github.sync667.CraftlandiaRails.CraftlandiaRails
version: 3.2.0
database: false
softdepend: [dynmap]
permissions:
    bytecart.*:
        description: give access to all blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7004: true
            bytecart.BC7005: true
            bytecart.BC7006: true
            bytecart.BC7007: true
            bytecart.BC7008: true
            bytecart.BC7009: true
            bytecart.BC7010: true
            bytecart.BC7011: true
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7015: true
            bytecart.BC7016: true
            bytecart.BC7017: true
            bytecart.BC7018: true
            bytecart.BC7019: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: true
            bytecart.BC8011: true
            bytecart.BC8020: true
            bytecart.BC8021: true
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true
            bytecart.BC9032: true
            bytecart.BC9064: true
            bytecart.BC9128: true
            bytecart.BC9037: true
            bytecart.BC9137: true
            bytecart.mego: true
            bytecart.sendto: true
            bytecart.bcupdater: true
            bytecart.bcreload: true
            bytecart.bcticket: true
            bytecart.bcback: true
            bytecart.bcdmapsync: true
            bytecart.bctracker: true
            bytecart.host.list: true
            bytecart.host.manager: true

    bytecart.helper:
        description: give access to small subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7004: true
            bytecart.BC7005: true
            bytecart.BC7006: true
            bytecart.BC7007: true
            bytecart.BC7008: true
            bytecart.BC7009: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7018: true
            bytecart.BC7019: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: false
            bytecart.BC8011: false
            bytecart.BC8020: false
            bytecart.BC8021: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: false
            bytecart.BC9016: false
            bytecart.BC9032: false
            bytecart.BC9064: false
            bytecart.BC9128: false
            bytecart.BC9037: false
            bytecart.BC9137: false
            bytecart.host.manager: true

    bytecart.subnetwork:
        description: give acces to all subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7004: true
            bytecart.BC7005: true
            bytecart.BC7006: true
            bytecart.BC7007: true
            bytecart.BC7008: true
            bytecart.BC7009: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7018: true
            bytecart.BC7019: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: false
            bytecart.BC8011: false
            bytecart.BC8020: false
            bytecart.BC8021: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true
            bytecart.BC9032: true
            bytecart.BC9064: true
            bytecart.BC9128: true
            bytecart.BC9037: true
            bytecart.BC9137: true
            bytecart.host.manager: true
    bytecart.BC7001:
        default: true
    bytecart.BC7002:
        default: true
    bytecart.BC7003:
        default: true
    bytecart.BC7004:
        default: true
    bytecart.BC7005:
        default: true
    bytecart.BC7006:
        default: true
    bytecart.BC7007:
        default: true
    bytecart.BC7008:
        default: true
    bytecart.BC7009:
        default: true
    bytecart.BC7010:
        default: true
    bytecart.BC7011:
        default: false
    bytecart.BC7012:
        default: true
    bytecart.BC7013:
        default: true
    bytecart.BC7014:
        default: true
    bytecart.BC7015:
        default: true
    bytecart.BC7016:
        default: true
    bytecart.BC7017:
        default: true
    bytecart.BC7018:
        default: true
    bytecart.BC7019:
        default: false
    bytecart.BC7020:
        default: true
    bytecart.BC7021:
        default: true
    bytecart.BC8010:
        default: false
    bytecart.BC8011:
        default: false
    bytecart.BC8020:
        default: false
    bytecart.BC8021:
        default: false
    bytecart.BC9000:
        default: false
    bytecart.BC9001:
        default: false
    bytecart.BC9002:
        default: false
    bytecart.BC9004:
        default: false
    bytecart.BC9008:
        default: false
    bytecart.BC9016:
        default: false
    bytecart.BC9032:
        default: false
    bytecart.BC9064:
        default: false
    bytecart.BC9128:
        default: false
    bytecart.BC9037:
        default: false
    bytecart.BC9137:
        default: false
    bytecart.mego:
        default: true
    bytecart.sendto:
        default: true
    bytecart.bcupdater:
        default: false
    bytecart.bcreload:
        default: false
    bytecart.bcticket:
        default: true
    bytecart.bcback:
        default: true
    bytecart.bcdmapsync:
        default: false
    bytecart.bctracker:
        default: false
    bytecart.bcsign:
        default: false
    bytecart.host.user:
        default: true
    bytecart.host.list:
        default: false
    bytecart.host.manager:
        default: false

commands:
    mego:
        description: set CraftlandiaRails destination address in your inventory
        usage: "Usage : /<command> address [train], where address is formatted as a.b.c"
        permission: bytecart.mego
        permission-message: You don't have permission <permission>

    sendto:
        description: set CraftlandiaRails destination address in a storage cart inventory
        usage: "Usage : /<command> address [train], where address is formatted as a.b.c"
        permission: bytecart.sendto
        permission-message: You don't have permission <permission>

    bcupdater:
        description: set a cart as Updater for CraftlandiaRails
        usage: |
           Usage : /<command> (region|local) n [new]
                     /<command> backbone
                     /<command> (reset_region|reset_local) n [full]
                     /<command> reset_backbone [full]
                     /<command> remove
        permission: bytecart.bcupdater
        permission-message: You don't have permission <permission>

    bcreload:
        description: reload configuration file
        usage: "Usage : /<command>"
        permission: bytecart.bcreload
        permission-message: You don't have permission <permission>
    bcticket:
        description: create a book ticket
        usage: |
           Usage : /<command> destination [train]
                   /<command> player destination [train]
        permission: bytecart.bcticket
        permission-message: You don't have permission <permission>
    bcback:
        description: go to return address
        usage: "Usage : /<command>"
        permission: bytecart.bcback
        permission-message: You don't have permission <permission>
    bcdmapsync:
        description: remove obsolete stations in dynmap
        usage: "Usage : /<command>"
        permission: bytecart.bcdmapsync
        permission-message: You don't have permission <permission>
    bctracker:
        description: list wanderers positions
        usage: "Usage : /<command>"
        permission: bytecart.bctracker
        permission-message: You don't have permission <permission>
    host:
        description: manage hostname records
        usage: |
           Usage : /<command> create hostname ip
                   /<command> remove hostname
                   /<command> [lookup] hostname|ip
                   /<command> list [page]
        permission: bytecart.host.user
        permission-message: You don't have permission <permission>